# Generated by Django 5.1.1 on 2024-09-13 16:44

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_date', models.DateField(null=True)),
                ('patient_name', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=50)),
                ('commission', models.IntegerField()),
                ('doctor_mobile', models.IntegerField(null=True)),
                ('doctor_email', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=50)),
                ('collection_status', models.CharField(choices=[('no', 'no'), ('yes', 'yes')], default='no', max_length=20)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TestField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('reference_range', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('age', models.CharField(max_length=4, null=True)),
                ('patient_address', models.CharField(max_length=50)),
                ('gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='details.gender')),
                ('title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='details.title')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('collected_date', models.DateField(null=True)),
                ('expected_complete_date', models.DateField(null=True)),
                ('created_at', models.DateTimeField(null=True, verbose_name=datetime.datetime(2024, 9, 13, 22, 14, 14, 416502))),
                ('order_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('collected_at', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='details.locations')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='details.customer')),
                ('referred_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='details.doctor')),
                ('tests', models.ManyToManyField(to='details.test')),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=20, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='details.order')),
                ('test_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.testfield')),
            ],
        ),
    ]
