# Generated by Django 4.1 on 2022-10-28 10:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=50)),
                ('commission', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('gender', models.CharField(choices=[('female', 'female'), ('male', 'male')], max_length=50)),
                ('collected_at', models.CharField(choices=[('ATP', 'ATP'), ('KNR', 'KNR')], max_length=50)),
                ('collected_date', models.DateField()),
                ('expected_complete_date', models.DateField()),
                ('created_at', models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 28, 16, 1, 21, 765876))),
                ('age', models.CharField(max_length=4, null=True)),
                ('name', models.CharField(max_length=50)),
                ('group', models.CharField(blank=True, choices=[('A', 'A'), ('AB', 'AB'), ('B', 'B'), ('O', 'O')], max_length=20)),
                ('rh', models.CharField(blank=True, choices=[('+', '+'), ('-', '-')], max_length=20)),
                ('WBC', models.CharField(blank=True, max_length=20)),
                ('RBC', models.CharField(blank=True, max_length=20)),
                ('platelets', models.CharField(blank=True, max_length=20)),
                ('left_eye', models.CharField(blank=True, max_length=20)),
                ('right_eye', models.CharField(blank=True, max_length=20)),
                ('bilrubine', models.CharField(blank=True, max_length=20)),
                ('referred_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='details.doctor')),
                ('tests', models.ManyToManyField(blank=True, to='details.test')),
            ],
        ),
    ]
