# Generated by Django 5.1.1 on 2024-09-13 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='test_field',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='order',
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2024, 9, 13, 22, 41, 21, 173273)),
        ),
        migrations.DeleteModel(
            name='TestField',
        ),
        migrations.DeleteModel(
            name='TestResult',
        ),
    ]
