# Generated by Django 5.1.1 on 2024-09-13 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0003_order_alb_glob_ratio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2024, 9, 13, 23, 32, 36, 668052)),
        ),
    ]
