# Generated by Django 4.1 on 2022-11-02 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0004_alter_patient_collected_at_alter_patient_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='WBC',
            field=models.CharField(blank=True, default='nil', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='collected_at',
            field=models.CharField(choices=[('ATP', 'ATP'), ('KNR', 'KNR')], max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2022, 11, 3, 0, 39, 21, 669842)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='group',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('O', 'O'), ('AB', 'AB')], max_length=20),
        ),
    ]
