# Generated by Django 5.1.1 on 2024-09-13 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0007_hb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hb',
            name='hb',
        ),
    ]
