# Generated by Django 4.2.15 on 2024-08-18 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0007_patient_collection_status_test_collection_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2024, 8, 18, 13, 52, 58, 327136)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='rh',
            field=models.CharField(blank=True, choices=[('+', '+'), ('-', '-')], max_length=20),
        ),
        migrations.AlterField(
            model_name='test',
            name='collection_status',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], max_length=20),
        ),
    ]
