# Generated by Django 5.1.1 on 2024-09-16 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0008_remove_hb_hb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hb',
            name='hb_reference_range',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='test',
            name='collection_status',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=20),
        ),
    ]
