# Generated by Django 4.2.15 on 2024-08-18 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0008_alter_patient_created_at_alter_patient_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2024, 8, 18, 14, 32, 57, 626449)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='group',
            field=models.CharField(blank=True, choices=[('O', 'O'), ('B', 'B'), ('A', 'A'), ('AB', 'AB')], max_length=20),
        ),
        migrations.AlterField(
            model_name='test',
            name='collection_status',
            field=models.CharField(choices=[('no', 'no'), ('yes', 'yes')], default='no', max_length=20),
        ),
    ]
