# Generated by Django 4.2.15 on 2024-08-18 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0009_alter_patient_created_at_alter_patient_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='collection_status',
            field=models.ManyToManyField(related_name='stat', to='details.test'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2024, 8, 18, 14, 35, 15, 287292)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='group',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('AB', 'AB'), ('B', 'B'), ('O', 'O')], max_length=20),
        ),
    ]
