# Generated by Django 5.1.1 on 2024-09-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0009_alter_hb_hb_reference_range_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UNITSANDRANGES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hba1c_unit', models.CharField(blank=True, max_length=10)),
                ('hba1c_reference_range', models.CharField(blank=True, max_length=150)),
                ('blood_urea_nitrogen_unit', models.CharField(blank=True, max_length=10)),
                ('blood_urea_nitrogen_reference_range', models.CharField(blank=True, max_length=150)),
                ('cotinine_unit', models.CharField(blank=True, max_length=10)),
                ('cotinine_reference_range', models.CharField(blank=True, max_length=150)),
                ('esr_1_hour_unit', models.CharField(blank=True, max_length=10)),
                ('esr_1_hour_reference_range', models.CharField(blank=True, max_length=150)),
                ('hbsag_unit', models.CharField(blank=True, max_length=10)),
                ('hbsag_reference_range', models.CharField(blank=True, max_length=150)),
                ('hiv_1_and_2_unit', models.CharField(blank=True, max_length=10)),
                ('hiv_1_and_2_reference_range', models.CharField(blank=True, max_length=150)),
                ('colour_unit', models.CharField(blank=True, max_length=10)),
                ('colour_reference_range', models.CharField(blank=True, max_length=150)),
                ('specific_gravity_unit', models.CharField(blank=True, max_length=10)),
                ('specific_gravity_reference_range', models.CharField(blank=True, max_length=150)),
                ('ph_unit', models.CharField(blank=True, max_length=10)),
                ('ph_reference_range', models.CharField(blank=True, max_length=150)),
                ('blood_unit', models.CharField(blank=True, max_length=10)),
                ('blood_reference_range', models.CharField(blank=True, max_length=150)),
                ('sugar_unit', models.CharField(blank=True, max_length=10)),
                ('sugar_reference_range', models.CharField(blank=True, max_length=150)),
                ('ketone_bodies_unit', models.CharField(blank=True, max_length=10)),
                ('ketone_bodies_reference_range', models.CharField(blank=True, max_length=150)),
                ('nitrite_unit', models.CharField(blank=True, max_length=10)),
                ('nitrite_reference_range', models.CharField(blank=True, max_length=150)),
                ('urobilinogen_unit', models.CharField(blank=True, max_length=10)),
                ('urobilinogen_reference_range', models.CharField(blank=True, max_length=150)),
                ('leucocytes_unit', models.CharField(blank=True, max_length=10)),
                ('leucocytes_reference_range', models.CharField(blank=True, max_length=150)),
                ('bile_salts_unit', models.CharField(blank=True, max_length=10)),
                ('bile_salts_reference_range', models.CharField(blank=True, max_length=150)),
                ('bile_pigments_unit', models.CharField(blank=True, max_length=10)),
                ('bile_pigments_reference_range', models.CharField(blank=True, max_length=150)),
                ('pus_cells_unit', models.CharField(blank=True, max_length=10)),
                ('pus_cells_reference_range', models.CharField(blank=True, max_length=150)),
                ('epithelial_cells_unit', models.CharField(blank=True, max_length=10)),
                ('epithelial_cells_reference_range', models.CharField(blank=True, max_length=150)),
                ('rbcs_unit', models.CharField(blank=True, max_length=10)),
                ('rbcs_reference_range', models.CharField(blank=True, max_length=150)),
                ('bacteria_unit', models.CharField(blank=True, max_length=10)),
                ('bacteria_reference_range', models.CharField(blank=True, max_length=150)),
                ('others_unit', models.CharField(blank=True, max_length=10)),
                ('others_reference_range', models.CharField(blank=True, max_length=150)),
                ('haemoglobin_unit', models.CharField(blank=True, max_length=10)),
                ('haemoglobin_reference_range', models.CharField(blank=True, max_length=150)),
                ('rbc_count_unit', models.CharField(blank=True, max_length=10)),
                ('rbc_count_reference_range', models.CharField(blank=True, max_length=150)),
                ('pcv_unit', models.CharField(blank=True, max_length=10)),
                ('pcv_reference_range', models.CharField(blank=True, max_length=150)),
                ('platelets_unit', models.CharField(blank=True, max_length=10)),
                ('platelets_reference_range', models.CharField(blank=True, max_length=150)),
                ('wbc_unit', models.CharField(blank=True, max_length=10)),
                ('wbc_reference_range', models.CharField(blank=True, max_length=150)),
                ('neutrophils_unit', models.CharField(blank=True, max_length=10)),
                ('neutrophils_reference_range', models.CharField(blank=True, max_length=150)),
                ('lymphocytes_unit', models.CharField(blank=True, max_length=10)),
                ('lymphocytes_reference_range', models.CharField(blank=True, max_length=150)),
                ('eosinophils_unit', models.CharField(blank=True, max_length=10)),
                ('eosinophils_reference_range', models.CharField(blank=True, max_length=150)),
                ('monocytes_unit', models.CharField(blank=True, max_length=10)),
                ('monocytes_reference_range', models.CharField(blank=True, max_length=150)),
                ('basophils_unit', models.CharField(blank=True, max_length=10)),
                ('basophils_reference_range', models.CharField(blank=True, max_length=150)),
                ('mcv_unit', models.CharField(blank=True, max_length=10)),
                ('mcv_reference_range', models.CharField(blank=True, max_length=150)),
                ('mchc_unit', models.CharField(blank=True, max_length=10)),
                ('mchc_reference_range', models.CharField(blank=True, max_length=150)),
                ('mch_unit', models.CharField(blank=True, max_length=10)),
                ('mch_reference_range', models.CharField(blank=True, max_length=150)),
                ('random_blood_sugar_unit', models.CharField(blank=True, max_length=10)),
                ('random_blood_sugar_reference_range', models.CharField(blank=True, max_length=150)),
                ('uric_acid_unit', models.CharField(blank=True, max_length=10)),
                ('uric_acid_reference_range', models.CharField(blank=True, max_length=150)),
                ('serum_creatinine_unit', models.CharField(blank=True, max_length=10)),
                ('serum_creatinine_reference_range', models.CharField(blank=True, max_length=150)),
                ('total_cholesterol_unit', models.CharField(blank=True, max_length=10)),
                ('total_cholesterol_reference_range', models.CharField(blank=True, max_length=150)),
                ('hdl_unit', models.CharField(blank=True, max_length=10)),
                ('hdl_reference_range', models.CharField(blank=True, max_length=150)),
                ('ldl_unit', models.CharField(blank=True, max_length=10)),
                ('ldl_reference_range', models.CharField(blank=True, max_length=150)),
                ('vldl_unit', models.CharField(blank=True, max_length=10)),
                ('vldl_reference_range', models.CharField(blank=True, max_length=150)),
                ('triglycerides_unit', models.CharField(blank=True, max_length=10)),
                ('triglycerides_reference_range', models.CharField(blank=True, max_length=150)),
                ('chol_hdl_ratio_unit', models.CharField(blank=True, max_length=10)),
                ('chol_hdl_ratio_reference_range', models.CharField(blank=True, max_length=150)),
                ('total_bilirubin_unit', models.CharField(blank=True, max_length=10)),
                ('total_bilirubin_reference_range', models.CharField(blank=True, max_length=150)),
                ('direct_bilirubin_unit', models.CharField(blank=True, max_length=10)),
                ('direct_bilirubin_reference_range', models.CharField(blank=True, max_length=150)),
                ('indirect_bilirubin_unit', models.CharField(blank=True, max_length=10)),
                ('indirect_bilirubin_reference_range', models.CharField(blank=True, max_length=150)),
                ('alkaline_phosphatase_unit', models.CharField(blank=True, max_length=10)),
                ('alkaline_phosphatase_reference_range', models.CharField(blank=True, max_length=150)),
                ('serum_gpt_unit', models.CharField(blank=True, max_length=10)),
                ('serum_gpt_reference_range', models.CharField(blank=True, max_length=150)),
                ('serum_got_unit', models.CharField(blank=True, max_length=10)),
                ('serum_got_reference_range', models.CharField(blank=True, max_length=150)),
                ('total_proteins_unit', models.CharField(blank=True, max_length=10)),
                ('total_proteins_reference_range', models.CharField(blank=True, max_length=150)),
                ('albumin_unit', models.CharField(blank=True, max_length=10)),
                ('albumin_reference_range', models.CharField(blank=True, max_length=150)),
                ('globulin_unit', models.CharField(blank=True, max_length=10)),
                ('globulin_reference_range', models.CharField(blank=True, max_length=150)),
                ('alb_glob_ratio_unit', models.CharField(blank=True, max_length=10)),
                ('alb_glob_ratio_reference_range', models.CharField(blank=True, max_length=150)),
                ('ggtp_unit', models.CharField(blank=True, max_length=10)),
                ('ggtp_reference_range', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='HB',
        ),
        migrations.RemoveField(
            model_name='order',
            name='alb_glob_ratio_reference_range',
        ),
        migrations.RemoveField(
            model_name='order',
            name='alb_glob_ratio_unit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='albumin_reference_range',
        ),
        migrations.RemoveField(
            model_name='order',
            name='albumin_unit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='alkaline_phosphatase_reference_range',
        ),
        migrations.RemoveField(
            model_name='order',
            name='alkaline_phosphatase_unit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='bacteria_reference_range',
        ),
        migrations.RemoveField(
            model_name='order',
            name='bacteria_unit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='basophils_reference_range',
        ),
        migrations.RemoveField(
            model_name='order',
            name='basophils_unit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='bile_pigments_reference_range',
        ),
        migrations.RemoveField(
            model_name='order',
            name='bile_pigments_unit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='bile_salts_reference_range',
        ),
        migrations.RemoveField(
            model_name='order',
            name='bile_salts_unit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='blood_reference_range',
        ),
        migrations.RemoveField(
            model_name='order',
            name='blood_unit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='blood_urea_nitrogen_reference_range',
        ),
        migrations.RemoveField(
            model_name='order',
            name='blood_urea_nitrogen_unit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='chol_hdl_ratio_reference_range',
        ),
        migrations.RemoveField(
            model_name='order',
            name='chol_hdl_ratio_unit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='colour_reference_range',
        ),
        migrations.RemoveField(
            model_name='order',
            name='colour_unit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cotinine_reference_range',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cotinine_unit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='direct_bilirubin_reference_range',
        ),
        migrations.RemoveField(
            model_name='order',
            name='direct_bilirubin_unit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='eosinophils_reference_range',
        ),
        migrations.RemoveField(
            model_name='order',
            name='eosinophils_unit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='epithelial_cells_reference_range',
        ),
        migrations.RemoveField(
            model_name='order',
            name='epithelial_cells_unit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='esr_1_hour_reference_range',
        ),
        migrations.RemoveField(
            model_name='order',
            name='esr_1_hour_unit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ggtp_reference_range',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ggtp_unit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='globulin_reference_range',
        ),
        migrations.RemoveField(
            model_name='order',
            name='globulin_unit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='haemoglobin_reference_range',
        ),
        migrations.RemoveField(
            model_name='order',
            name='haemoglobin_unit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='hba1c_reference_range',
        ),
        migrations.RemoveField(
            model_name='order',
            name='hba1c_unit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='hbsag_reference_range',
        ),
        migrations.RemoveField(
            model_name='order',
            name='hbsag_unit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='hdl_reference_range',
        ),
        migrations.RemoveField(
            model_name='order',
            name='hdl_unit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='hiv_1_and_2_reference_range',
        ),
        migrations.RemoveField(
            model_name='order',
            name='hiv_1_and_2_unit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='indirect_bilirubin_reference_range',
        ),
        migrations.RemoveField(
            model_name='order',
            name='indirect_bilirubin_unit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ketone_bodies_reference_range',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ketone_bodies_unit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ldl_reference_range',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ldl_unit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='leucocytes_reference_range',
        ),
        migrations.RemoveField(
            model_name='order',
            name='leucocytes_unit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='lymphocytes_reference_range',
        ),
        migrations.RemoveField(
            model_name='order',
            name='lymphocytes_unit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='mch_reference_range',
        ),
        migrations.RemoveField(
            model_name='order',
            name='mch_unit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='mchc_reference_range',
        ),
        migrations.RemoveField(
            model_name='order',
            name='mchc_unit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='mcv_reference_range',
        ),
        migrations.RemoveField(
            model_name='order',
            name='mcv_unit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='monocytes_reference_range',
        ),
        migrations.RemoveField(
            model_name='order',
            name='monocytes_unit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='neutrophils_reference_range',
        ),
        migrations.RemoveField(
            model_name='order',
            name='neutrophils_unit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='nitrite_reference_range',
        ),
        migrations.RemoveField(
            model_name='order',
            name='nitrite_unit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='others_reference_range',
        ),
        migrations.RemoveField(
            model_name='order',
            name='others_unit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pcv_reference_range',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pcv_unit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ph_reference_range',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ph_unit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='platelets_reference_range',
        ),
        migrations.RemoveField(
            model_name='order',
            name='platelets_unit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pus_cells_reference_range',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pus_cells_unit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='random_blood_sugar_reference_range',
        ),
        migrations.RemoveField(
            model_name='order',
            name='random_blood_sugar_unit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='rbc_count_reference_range',
        ),
        migrations.RemoveField(
            model_name='order',
            name='rbc_count_unit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='rbcs_reference_range',
        ),
        migrations.RemoveField(
            model_name='order',
            name='rbcs_unit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='serum_creatinine_reference_range',
        ),
        migrations.RemoveField(
            model_name='order',
            name='serum_creatinine_unit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='serum_got_reference_range',
        ),
        migrations.RemoveField(
            model_name='order',
            name='serum_got_unit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='serum_gpt_reference_range',
        ),
        migrations.RemoveField(
            model_name='order',
            name='serum_gpt_unit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='specific_gravity_reference_range',
        ),
        migrations.RemoveField(
            model_name='order',
            name='specific_gravity_unit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sugar_reference_range',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sugar_unit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_bilirubin_reference_range',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_bilirubin_unit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_cholesterol_reference_range',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_cholesterol_unit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_proteins_reference_range',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_proteins_unit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='triglycerides_reference_range',
        ),
        migrations.RemoveField(
            model_name='order',
            name='triglycerides_unit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='uric_acid_reference_range',
        ),
        migrations.RemoveField(
            model_name='order',
            name='uric_acid_unit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='urobilinogen_reference_range',
        ),
        migrations.RemoveField(
            model_name='order',
            name='urobilinogen_unit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='vldl_reference_range',
        ),
        migrations.RemoveField(
            model_name='order',
            name='vldl_unit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='wbc_reference_range',
        ),
        migrations.RemoveField(
            model_name='order',
            name='wbc_unit',
        ),
        migrations.AlterField(
            model_name='customer',
            name='patient_address',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='test',
            name='collection_status',
            field=models.CharField(choices=[('no', 'no'), ('yes', 'yes')], default='no', max_length=20),
        ),
    ]
