# Generated by Django 4.2.15 on 2024-08-18 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0010_alter_patient_collection_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='collected_at',
            field=models.CharField(choices=[('KNR', 'KNR'), ('ATP', 'ATP')], max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2024, 8, 18, 16, 15, 28, 207462)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='group',
            field=models.CharField(blank=True, choices=[('O', 'O'), ('AB', 'AB'), ('B', 'B'), ('A', 'A')], max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='rh',
            field=models.CharField(blank=True, choices=[('-', '-'), ('+', '+')], max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tests',
            field=models.ManyToManyField(to='details.test'),
        ),
    ]
