# Generated by Django 5.1.1 on 2024-09-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0010_unitsandranges_delete_hb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitsandranges',
            name='hba1c_reference_range',
            field=models.TextField(blank=True),
        ),
    ]
