# Generated by Django 4.2.15 on 2024-09-04 12:05

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0011_alter_patient_collected_at_alter_patient_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('gender', models.CharField(choices=[('female', 'female'), ('male', 'male')], max_length=50)),
                ('age', models.CharField(max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('collected_at', models.CharField(choices=[('ATP', 'ATP'), ('KNR', 'KNR')], max_length=50)),
                ('collected_date', models.DateField(null=True)),
                ('expected_complete_date', models.DateField(null=True)),
                ('created_at', models.DateTimeField(null=True, verbose_name=datetime.datetime(2024, 9, 4, 12, 5, 33, 142717))),
                ('order_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('group', models.CharField(blank=True, choices=[('O', 'O'), ('A', 'A'), ('B', 'B'), ('AB', 'AB')], max_length=20)),
                ('rh', models.CharField(blank=True, choices=[('-', '-'), ('+', '+')], max_length=20)),
                ('WBC', models.CharField(blank=True, default='nil', max_length=20)),
                ('RBC', models.CharField(blank=True, max_length=20)),
                ('platelets', models.CharField(blank=True, max_length=20)),
                ('left_eye', models.CharField(blank=True, max_length=20)),
                ('right_eye', models.CharField(blank=True, max_length=20)),
                ('bilrubine', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='test',
            name='collection_status',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=20),
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.AddField(
            model_name='order',
            name='collection_status',
            field=models.ManyToManyField(related_name='stat', to='details.test'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='details.customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='referred_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='details.doctor'),
        ),
        migrations.AddField(
            model_name='order',
            name='tests',
            field=models.ManyToManyField(to='details.test'),
        ),
    ]
