# Generated by Django 5.1.1 on 2024-09-16 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0012_tech_alter_test_collection_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='collected_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='collected_by', to='details.tech'),
        ),
        migrations.AddField(
            model_name='order',
            name='report_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='report_by', to='details.tech'),
        ),
        migrations.AddField(
            model_name='order',
            name='tested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tested_by', to='details.tech'),
        ),
    ]
