# Generated by Django 4.2.15 on 2024-09-07 10:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0012_customer_date_order_alter_test_collection_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_date', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='collected_at',
            field=models.CharField(choices=[('KNR', 'KNR'), ('ATP', 'ATP')], max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2024, 9, 7, 10, 44, 47, 668863)),
        ),
        migrations.AlterField(
            model_name='order',
            name='group',
            field=models.CharField(blank=True, choices=[('B', 'B'), ('O', 'O'), ('A', 'A'), ('AB', 'AB')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='rh',
            field=models.CharField(blank=True, choices=[('+', '+'), ('-', '-')], max_length=20),
        ),
    ]
