# Generated by Django 5.1.1 on 2024-09-16 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0013_order_collected_by_order_report_by_order_tested_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='collected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='collected_by', to='details.tech'),
        ),
        migrations.AlterField(
            model_name='order',
            name='report_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='report_by', to='details.tech'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tested_by', to='details.tech'),
        ),
    ]
