# Generated by Django 4.2.15 on 2024-09-07 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0014_alter_order_collected_at_alter_order_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2024, 9, 7, 10, 49, 46, 336734)),
        ),
        migrations.AlterField(
            model_name='order',
            name='group',
            field=models.CharField(blank=True, choices=[('AB', 'AB'), ('B', 'B'), ('O', 'O'), ('A', 'A')], max_length=20),
        ),
    ]
