# Generated by Django 5.1.1 on 2024-09-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0015_order_collected_datetime_order_report_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='collected_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='report_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='tested_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
