# Generated by Django 4.2.15 on 2024-09-07 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0015_alter_order_created_at_alter_order_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locations',
            old_name='required_date',
            new_name='location',
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2024, 9, 7, 10, 53, 59, 233825)),
        ),
        migrations.AlterField(
            model_name='order',
            name='group',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('O', 'O'), ('AB', 'AB'), ('B', 'B')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='rh',
            field=models.CharField(blank=True, choices=[('-', '-'), ('+', '+')], max_length=20),
        ),
        migrations.AlterField(
            model_name='test',
            name='collection_status',
            field=models.CharField(choices=[('no', 'no'), ('yes', 'yes')], default='no', max_length=20),
        ),
    ]
