# Generated by Django 5.1.1 on 2024-10-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0016_alter_order_collected_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitsandranges',
            name='alb_glob_ratio_reference_range',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='unitsandranges',
            name='albumin_reference_range',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='unitsandranges',
            name='alkaline_phosphatase_reference_range',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='unitsandranges',
            name='bacteria_reference_range',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='unitsandranges',
            name='basophils_reference_range',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='unitsandranges',
            name='bile_pigments_reference_range',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='unitsandranges',
            name='bile_salts_reference_range',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='unitsandranges',
            name='blood_reference_range',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='unitsandranges',
            name='blood_urea_nitrogen_reference_range',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='unitsandranges',
            name='chol_hdl_ratio_reference_range',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='unitsandranges',
            name='colour_reference_range',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='unitsandranges',
            name='cotinine_reference_range',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='unitsandranges',
            name='direct_bilirubin_reference_range',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='unitsandranges',
            name='eosinophils_reference_range',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='unitsandranges',
            name='epithelial_cells_reference_range',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='unitsandranges',
            name='esr_1_hour_reference_range',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='unitsandranges',
            name='ggtp_reference_range',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='unitsandranges',
            name='globulin_reference_range',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='unitsandranges',
            name='haemoglobin_reference_range',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='unitsandranges',
            name='hbsag_reference_range',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='unitsandranges',
            name='hdl_reference_range',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='unitsandranges',
            name='hiv_1_and_2_reference_range',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='unitsandranges',
            name='indirect_bilirubin_reference_range',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='unitsandranges',
            name='ketone_bodies_reference_range',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='unitsandranges',
            name='ldl_reference_range',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='unitsandranges',
            name='leucocytes_reference_range',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='unitsandranges',
            name='lymphocytes_reference_range',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='unitsandranges',
            name='mch_reference_range',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='unitsandranges',
            name='mchc_reference_range',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='unitsandranges',
            name='mcv_reference_range',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='unitsandranges',
            name='monocytes_reference_range',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='unitsandranges',
            name='neutrophils_reference_range',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='unitsandranges',
            name='nitrite_reference_range',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='unitsandranges',
            name='others_reference_range',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='unitsandranges',
            name='pcv_reference_range',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='unitsandranges',
            name='ph_reference_range',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='unitsandranges',
            name='platelets_reference_range',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='unitsandranges',
            name='pus_cells_reference_range',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='unitsandranges',
            name='random_blood_sugar_reference_range',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='unitsandranges',
            name='rbc_count_reference_range',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='unitsandranges',
            name='rbcs_reference_range',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='unitsandranges',
            name='serum_creatinine_reference_range',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='unitsandranges',
            name='serum_got_reference_range',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='unitsandranges',
            name='serum_gpt_reference_range',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='unitsandranges',
            name='specific_gravity_reference_range',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='unitsandranges',
            name='sugar_reference_range',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='unitsandranges',
            name='total_bilirubin_reference_range',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='unitsandranges',
            name='total_cholesterol_reference_range',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='unitsandranges',
            name='total_proteins_reference_range',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='unitsandranges',
            name='triglycerides_reference_range',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='unitsandranges',
            name='uric_acid_reference_range',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='unitsandranges',
            name='urobilinogen_reference_range',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='unitsandranges',
            name='vldl_reference_range',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='unitsandranges',
            name='wbc_reference_range',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
