# Generated by Django 4.2.15 on 2024-09-07 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0017_gender_alter_order_created_at_alter_order_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('female', 'female'), ('male', 'male')], max_length=50),
        ),
        migrations.AlterField(
            model_name='gender',
            name='required_date',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2024, 9, 7, 13, 45, 55, 804040)),
        ),
        migrations.AlterField(
            model_name='order',
            name='group',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('O', 'O'), ('B', 'B'), ('AB', 'AB')], max_length=20),
        ),
    ]
