# Generated by Django 5.1.1 on 2024-10-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0017_alter_unitsandranges_alb_glob_ratio_reference_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='willing_to_get_SMS',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='collection_status',
            field=models.CharField(choices=[('no', 'no'), ('yes', 'yes')], default='no', max_length=20),
        ),
    ]
