# Generated by Django 4.2.15 on 2024-09-07 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0018_alter_customer_gender_alter_gender_required_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='required_date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2024, 9, 7, 13, 47, 10, 900143)),
        ),
        migrations.AlterField(
            model_name='order',
            name='group',
            field=models.CharField(blank=True, choices=[('B', 'B'), ('O', 'O'), ('AB', 'AB'), ('A', 'A')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='rh',
            field=models.CharField(blank=True, choices=[('-', '-'), ('+', '+')], max_length=20),
        ),
    ]
