# Generated by Django 5.1.1 on 2024-10-03 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0018_customer_willing_to_get_sms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='willing_to_get_SMS',
        ),
    ]
