# Generated by Django 4.2.15 on 2024-09-07 13:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0019_alter_gender_required_date_alter_order_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gender',
            old_name='required_date',
            new_name='gender',
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='details.gender'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2024, 9, 7, 13, 53, 35, 931956)),
        ),
        migrations.AlterField(
            model_name='order',
            name='group',
            field=models.CharField(blank=True, choices=[('B', 'B'), ('A', 'A'), ('AB', 'AB'), ('O', 'O')], max_length=20),
        ),
        migrations.AlterField(
            model_name='test',
            name='collection_status',
            field=models.CharField(choices=[('no', 'no'), ('yes', 'yes')], default='no', max_length=20),
        ),
    ]
