# Generated by Django 5.1.1 on 2024-10-07 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0019_remove_customer_willing_to_get_sms'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('canceled', 'Canceled')], max_length=20)),
                ('notes', models.CharField(blank=True, max_length=50, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.customer')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.tech')),
            ],
        ),
    ]
