# Generated by Django 5.1.1 on 2024-10-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0020_homevisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='homevisit',
            name='googlemaps_link',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='test',
            name='collection_status',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=20),
        ),
    ]
