# Generated by Django 5.1.1 on 2024-10-07 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0022_visitstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homevisit',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.visitstatus'),
        ),
        migrations.AlterField(
            model_name='test',
            name='collection_status',
            field=models.CharField(choices=[('no', 'no'), ('yes', 'yes')], default='no', max_length=20),
        ),
    ]
