# Generated by Django 5.1.1 on 2024-09-09 08:28

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0023_title_alter_order_created_at_alter_order_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='details.title'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='doctor_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='doctor_mobile',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2024, 9, 9, 8, 28, 58, 313768)),
        ),
        migrations.AlterField(
            model_name='order',
            name='group',
            field=models.CharField(blank=True, choices=[('O', 'O'), ('AB', 'AB'), ('B', 'B'), ('A', 'A')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='rh',
            field=models.CharField(blank=True, choices=[('+', '+'), ('-', '-')], max_length=20),
        ),
        migrations.AlterField(
            model_name='test',
            name='collection_status',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=20),
        ),
    ]
