# Generated by Django 5.1.1 on 2024-09-09 08:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0024_customer_title_doctor_doctor_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='patient_address',
            field=models.CharField(default='hyd', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2024, 9, 9, 8, 34, 38, 966877)),
        ),
        migrations.AlterField(
            model_name='order',
            name='group',
            field=models.CharField(blank=True, choices=[('AB', 'AB'), ('O', 'O'), ('A', 'A'), ('B', 'B')], max_length=20),
        ),
        migrations.AlterField(
            model_name='test',
            name='collection_status',
            field=models.CharField(choices=[('no', 'no'), ('yes', 'yes')], default='no', max_length=20),
        ),
    ]
