# Generated by Django 5.1.1 on 2024-10-14 18:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0026_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homevisit',
            name='date',
        ),
        migrations.AddField(
            model_name='homevisit',
            name='visit_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
